name: Faculty
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  jobrun-selfhosted:
    name: Trigger Job on Self-hosted Runner
    runs-on: self-hosted
    env:
      FACULTY_JOB_NAME: ${{ secrets.FACULTY_JOB_NAME }}
    steps:
      - uses: actions/checkout@v2
      # We should already have python/pip/... installed
      - name: Python version
        run: python -V
      - name: Install any workflow requirements
        run: |
          pip install -r workflow/workflow_requirements.txt
      - name: Run a job
        run: python workflow/jobrun.py
